### ISSUE TITLE
关于Figure3b的图

### ISSUE THREAD

**Issue by CQMUyan** [yz3n18/Neuroblastoma#1]
请问一下能否提供figure3C D的WGCNA的网络图代码

**Comment by yz3n18** [comment]
Hello @CQMUyan ，感谢您的关注，figure3C/D的图是通过以下步骤产生的：

1）通过WCGNA进行共表达模块的计算，这一步是按照WGCNA的标准代码，也可以参考 Figure 3 and S5.R 中的 Supplementary Figure 5 WGCNA 或者文章中的补充材料Supplementary Table 6 sheet1。
2）将得到的基因，WGCNA的模块信息，表达量信息，通路信息添加到**gephi**软件中进行绘图。

希望有所帮助！

**Comment by CQMUyan** [comment]
谢谢，您的研究非常有意义，我将继续follow您的研究
